### PR TITLE
write method for total sum

### PR DESCRIPTION
**Pull request by agni1402**
add: sum method
This method helps the user to find the total sum of all elements which are of data type(Integer, Float, Double).
Review my code and Please merge my PR.

### CODE REVIEW

**Comment by harsh9539** [comment]
But if user make list of strings how this method handle that case. 

Please handle that case also I will merge your code

**Comment by agni1402** [comment]
I have made all of the changes and also removed some common errors in the code that affect the compilation of the program and also created the isEmpty() method for checking whether the list is empty or not and put a check in the sum method.
Review my latest commit and Please merge my PR.
Thank you.

**Comment by agni1402** [comment]
Sir, Waiting for your review.

**Comment by agni1402** [comment]
I have made all changes. Review and Please merge my PR.

**Pull request merged**
